use assert_cmd::Command;
use std::fs;
use tempfile::TempDir;

fn rex_cmd() -> Command {
    Command::cargo_bin("rex").expect("rex binary must be built")
}

#[test]
fn codebase_writes_tree_for_synthetic_dir() {
    let dir = TempDir::new().unwrap();
    let root = dir.path();

    fs::create_dir_all(root.join("src/bundle")).unwrap();
    fs::create_dir_all(root.join("src/commands")).unwrap();
    fs::write(root.join("src/bundle/mod.rs"), "").unwrap();
    fs::write(root.join("src/bundle/manifest.rs"), "").unwrap();
    fs::write(root.join("src/commands/create.rs"), "").unwrap();
    fs::write(root.join("src/commands/codebase.rs"), "").unwrap();
    fs::write(root.join("README.md"), "").unwrap();

    rex_cmd().arg("codebase").current_dir(root).assert().success();

    let body = fs::read_to_string(root.join("CODEBASE.md")).unwrap();

    // OsStr::cmp is byte-order: uppercase R (0x52) sorts before lowercase s (0x73)
    let expected_block = "\
README.md
src/
  bundle/
    manifest.rs
    mod.rs
  commands/
    codebase.rs
    create.rs
";
    assert!(
        body.contains(expected_block),
        "CODEBASE.md missing expected tree block:\n{body}"
    );
    assert!(body.starts_with("# Codebase\n"));
    assert!(body.contains("Generated by `rex codebase`"));
    assert!(!body.contains("\nCODEBASE.md\n"));
}

#[test]
fn codebase_skips_gitignore_and_dotfolders() {
    let dir = TempDir::new().unwrap();
    let root = dir.path();

    fs::write(root.join(".gitignore"), "ignored/\nsecret.txt\n").unwrap();
    fs::create_dir_all(root.join("ignored")).unwrap();
    fs::write(root.join("ignored/x.rs"), "").unwrap();
    fs::write(root.join("secret.txt"), "").unwrap();
    fs::create_dir_all(root.join(".git")).unwrap();
    fs::write(root.join(".git/config"), "").unwrap();
    fs::create_dir_all(root.join(".vscode")).unwrap();
    fs::write(root.join(".vscode/settings.json"), "").unwrap();
    fs::write(root.join("kept.rs"), "").unwrap();

    rex_cmd().arg("codebase").current_dir(root).assert().success();

    let body = fs::read_to_string(root.join("CODEBASE.md")).unwrap();
    assert!(body.contains("kept.rs"));
    assert!(!body.contains("ignored"));
    assert!(!body.contains("secret.txt"));
    assert!(!body.contains(".git"));
    assert!(!body.contains(".vscode"));
}

#[test]
fn codebase_is_idempotent() {
    let dir = TempDir::new().unwrap();
    let root = dir.path();
    fs::create_dir_all(root.join("src")).unwrap();
    fs::write(root.join("src/main.rs"), "").unwrap();

    rex_cmd().arg("codebase").current_dir(root).assert().success();
    let first = fs::read_to_string(root.join("CODEBASE.md")).unwrap();
    rex_cmd().arg("codebase").current_dir(root).assert().success();
    let second = fs::read_to_string(root.join("CODEBASE.md")).unwrap();
    assert_eq!(first, second, "CODEBASE.md must be idempotent");
}
